title: ClassConnect User Manual
description: Documentation for ClassConnect learning management system
theme: just-the-docs

# Base configuration
url: "https://classconnect13.github.io"
baseurl: "/app-manual"  # Keep this since we're using /app-manual/

# Disable all default Just the Docs collections
collections_dir: ""
collections: {}

# Hide unwanted default pages
hide:
  - CHANGELOG
  - LICENSE
  - README
  - CODE_OF_CONDUCT
  - CONTRIBUTING
  - SECURITY
  - search

# Navigation configuration
nav_external_links: false  # Disable external nav

# Explicit navigation order (matches your index.md)
nav_order:
  - index.md
  - getting-started
  - app-navigation
  - profile
  - courses
  - feedbacks

# Just the Docs specific settings
just_the_docs:
  # Disable all default collections
  collections:
    config: false
    ui_components: false
    typography: false
    buttons: false
    labels: false
    tables: false
    lists: false
    code: false
    callouts: false
    utilities: false
    layout: false
    navigation: false
    customization: false
  
  # Optional customization
  logo: "assets/images/logo.png"
  dark_mode: true
  color_scheme: "classconnect"

# Plugin management (empty unless you add specific plugins)
plugins: []