title: ClassConnect User Manual
description: Documentation for ClassConnect learning management system
theme: just-the-docs

# Base configuration
url: "https://classconnect13.github.io"
baseurl: "/app-manual"

# Collections for automatic navigation
collections:
  getting_started:
    title: Getting Started
    output: true
  app_navigation:
    title: App Navigation
    output: true
  profile:
    title: Profile
    output: true
  courses:
    title: Courses
    output: true
  feedbacks:
    title: Feedbacks
    output: true

# Default front matter values
defaults:
  - scope:
      path: "getting-started"
      type: getting_started
    values:
      layout: default
      nav_order: 1
  - scope:
      path: "app-navigation"
      type: app_navigation
    values:
      layout: default
      nav_order: 2
  - scope:
      path: "profile"
      type: profile
    values:
      layout: default
      nav_order: 3
  - scope:
      path: "courses"
      type: courses
    values:
      layout: default
      nav_order: 4
  - scope:
      path: "feedbacks"
      type: feedbacks
    values:
      layout: default
      nav_order: 5

# Just the Docs settings
just_the_docs:
  collections:
    getting_started:
      name: Getting Started
    app_navigation:
      name: App Navigation
    profile:
      name: Profile
    courses:
      name: Courses
    feedbacks:
      name: Feedbacks